.\" $Id: mediancp.1,v 1.2 2006/01/26 22:22:54 ucacpco Exp $

.TH mediancp 1

.SH NAME
mediancp \- Computes the median connection probability over an ROI

.SH SYNOPSIS
.B mediancp \fR <\fIinputroot\fR> <\fIoutputroot\fR> [\fB\-pd\fR <\fIp\fR>] [\fB\-targetindex\fR <\fIindex\fR>]

.SH DESCRIPTION

Computes the median CP over an ROI. The output is an Analyze volume containing the median
value of each voxel over all images.

.SH "AUTHORS"
Philip Cook <camino@cs.ucl.ac.uk>

.SH "SEE ALSO"
track(1), picopdfs(1)

.SH BUGS
