.\" $Id: mincp.1,v 1.2 2006/01/26 22:22:54 ucacpco Exp $

.TH mincp 1

.SH NAME
mincp \- Computes the minimum connection probability over and ROI

.SH SYNOPSIS
.B mincp \fR <\fIinputroot\fR> <\fIoutputroot\fR> [\fB\-pd\fR <\fIp\fR>] [\fB\-targetindex\fR <\fIindex\fR>]

.SH DESCRIPTION

Computes the minimum connection probability over an ROI. The output is an Analyze volume
containing the minimum value of each voxel over all images.

.SH "AUTHORS"
Philip Cook <camino@cs.ucl.ac.uk>

.SH "SEE ALSO"
track(1), picopdfs(1), cpstats(1)

.SH BUGS
